# Use the official Apache Airflow image as the base
FROM apache/airflow:latest
COPY requirements.txt /requirements.txt
RUN pip install --user --upgrade pip
RUN pip install --no-cache-dir --user -r /requirements.txt
# USER root
# # Install necessary system packages
# RUN apt-get update && \
#     apt-get install -y --no-install-recommends \
#     gcc \
#     && apt-get clean
# # Switch back to the airflow user
# USER airflow
