version: '3'

services:
  airflow-bibek:
    image: airflow-bibek:latest
    volumes:
      - ./airflow:/opt/airflow
    ports:
      - "8080:8080"
    command: airflow standalone

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo 10.10.10.60:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    volumes:
      - ./mongodb_data:/data/db
    depends_on:
      - airflow-bibek
